name: CI General

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Check if package-lock.json is up to date
        run: npx --yes package-lock-utd@1.1.3

      - name: Install libs required for linting
        run: npm install

      - name: Formatting check
        run: npm run format-check
