name: CI

on:
  push:

jobs:
  libs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Check if package-lock.json is up to date
        run: npx --yes package-lock-utd@1.1.3

  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          
      - name: Run Biome
        run: biome ci --changed --no-errors-on-unmatched .
